name: "1st pipeline"

on: workflow_dispatch
  # push:
  #   branches: 
      # - 'feature/**'
      # - 'main'

permissions: 
  id-token: write
  contents: read
  
jobs: 
  terraform_init_plan:
    runs-on: newrunner
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        # create app in azureportel fill details like git id , repo name , branch(optional), permissions block dena padega
        # nahi to error ayega
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          # ClientId of the Azure Service principal created.
          client-id: 1c035810-e64d-42b4-b399-6973734a9302
          # TenantId of the Azure Service principal created.
          tenant-id: e66a3e9f-8b6b-4541-aa09-a25d0fbce6b1
          # Azure subscriptionId
          subscription-id: b43bd80e-9eef-4206-b932-7dba68f2f340
 
      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: env/preprod

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        working-directory: env/preprod
        continue-on-error: true

      - name: Terraform validate
        id: validate
        run: terraform validate -no-color
        working-directory: env/preprod

      - name: Terraform Plan
        id: Plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: env/preprod
  terraform_apply:
    environment: dev
    runs-on: newrunner
    needs: terraform_init_plan
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        # create app in azureportel fill details like git id , repo name , branch(optional), permissions block dena padega
        # nahi to error ayega
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          # ClientId of the Azure Service principal created.
          client-id: 1c035810-e64d-42b4-b399-6973734a9302
          # TenantId of the Azure Service principal created.
          tenant-id: e66a3e9f-8b6b-4541-aa09-a25d0fbce6b1
          # Azure subscriptionId
          subscription-id: b43bd80e-9eef-4206-b932-7dba68f2f340
 
      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: env/preprod

      - name: Terraform validate
        id: validate
        run: terraform validate -no-color
        working-directory: env/preprod

      - name: Terraform Apply
        id: Apply
        run: terraform apply -auto-approve
        working-directory: env/preprod

          
         
          
          
