name: "1st pipeline"

on: workflow_dispatch
  # push:
  #   branches: 
      # - 'feature/**'
      # - 'main'
jobs: 
  terraform_init:
    name: Terraform Init
    runs-on: newrunner
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        
