name: "1st pipeline"

on: workflow_dispatch
  # push:
  #   branches: 
      # - 'feature/**'
      # - 'main'

permissions: 
  id-token: write
  contents: read
  
jobs: 
  terraform_jobs:
    runs-on: newrunner
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        # create app in azureportel fill details like git id , repo name , branch(optional)
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          # ClientId of the Azure Service principal created.
          client-id: 1c035810-e64d-42b4-b399-6973734a9302
          # TenantId of the Azure Service principal created.
          tenant-id: e66a3e9f-8b6b-4541-aa09-a25d0fbce6b1
          # Azure subscriptionId
          subscription-id: b43bd80e-9eef-4206-b932-7dba68f2f340
          # Set this value to true to enable Azure PowerShell Login in addition to Azure CLI login
         
          
          
