name: "Github-Action-Pipeline"

on: 
  #app rejistration ke liye main credential ke time org , repo pull request lena padega or env bhi set kerna hoga or branch main bhi
  pull_request:
    branches: 
      # - 'feature/**'
      - 'main'
  push:
    branches: 
      - 'main'

permissions: 
  id-token: write
  contents: read
  
jobs: 
  terraform_init_plan:
    runs-on: newrunner
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
        # create app in azureportel fill details like git id , repo name , branch(optional), permissions block dena padega
        # nahi to error ayega
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: 1c035810-e64d-42b4-b399-6973734a9302
          tenant-id: e66a3e9f-8b6b-4541-aa09-a25d0fbce6b1
          # Azure subscriptionId
          subscription-id: b43bd80e-9eef-4206-b932-7dba68f2f340
 
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: env/preprod

      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        working-directory: env/preprod
        continue-on-error: true

      - name: Terraform validate
        id: validate
        run: terraform validate
        working-directory: env/preprod

      - name: Terraform Plan
        id: Plan
        run: terraform plan -out=tfplan
        continue-on-error: true
        working-directory: env/preprod
      - name: Save Terraform Plan
        id: SavePlan
        uses: actions/upload-artifacts@v3
        with:
          name: tfplan
          path: tfplan
          
  terraform_apply:
    if: github.ref == 'refs/heads/main'
    environment: dev
    runs-on: newrunner
    needs: terraform_init_plan
    permissions:
      id-token: write
      contents: read
    
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0

      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          # ClientId of the Azure Service principal created.
          client-id: 1c035810-e64d-42b4-b399-6973734a9302
          # TenantId of the Azure Service principal created.
          tenant-id: e66a3e9f-8b6b-4541-aa09-a25d0fbce6b1
          # Azure subscriptionId
          subscription-id: b43bd80e-9eef-4206-b932-7dba68f2f340
 
      - name: Terraform Init
        id: init
        run: terraform init
        working-directory: env/preprod

      - name: Download terraform Plan
        id: DownloadPlan
        uses: actions/download-artifacts@v3
        with:
          name: tfplan
          path: tfplan
      

      - name: Terraform Apply
        id: Apply
        # run: terraform apply -auto-approve
        run: terraform apply tfplan
        # working-directory: env/preprod

          
         
          
          
